name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run black
        run: pre-commit run black --all-files

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run isort
        run: pre-commit run isort --all-files

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run flake8
        run: pre-commit run flake8 --all-files

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run pylint
        run: pre-commit run pylint --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run tests
        run: pre-commit run pytest
