name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run black
        id: run_black
        continue-on-error: true
        run: pre-commit run black --all-files
      - name: Commit formatting changes
        if: steps.run_black.outcome == 'failure'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: format with black"
            BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            git push origin HEAD:$BRANCH
          fi

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run isort
        id: run_isort
        continue-on-error: true
        run: pre-commit run isort --all-files
      - name: Commit import sorting changes
        if: steps.run_isort.outcome == 'failure'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: sort imports"
            BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            git push origin HEAD:$BRANCH
          fi

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run flake8
        run: pre-commit run flake8 --all-files

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run pylint
        id: pylint
        run: |
          set +e
          pre-commit run pylint --all-files | tee pylint.log
          ret=${PIPESTATUS[0]}
          grep -oE 'rated at [0-9.]+' pylint.log | awk '{print $3}' > score.txt
          echo "score=$(cat score.txt)" >> "$GITHUB_OUTPUT"
          exit 0
      - name: Generate pylint badge
        run: |
          python scripts/pylint_badge.py pylint.log docs/pylint.svg
      - uses: actions/upload-artifact@v4
        with:
          name: pylint-badge
          path: docs/pylint.svg
      - name: Commit pylint badge
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          if [ -n "$(git status --porcelain docs/pylint.svg)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/pylint.svg
            git commit -m "docs: update pylint badge" || true
            git push
          fi

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          pre-commit install-hooks
      - name: Run tests with coverage
        run: coverage run -m pytest
      - name: Generate coverage report
        run: |
          coverage xml -o coverage.xml
          coverage-badge -f -o docs/coverage.svg
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            docs/coverage.svg
      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && always()
        run: |
          if [ -n "$(git status --porcelain docs/coverage.svg)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/coverage.svg
            git commit -m "docs: update coverage badge" || true
            git push
          fi
